
#
# Redis Dockerfile
#
FROM centos:7

COPY redis-6.2.1.tar.gz /redis-6.2.1.tar.gz

# Install Redis.
RUN \
  yum install make -y && \
  yum groupinstall 'Development Tools' -y && \
  cd / && \
  tar xvzf redis-6.2.1.tar.gz && \
  cd redis-6.2.1 && \
  make && \
  make install && \
  cp -f src/redis-sentinel /usr/local/bin && \
  mkdir -p /etc/redis && \
  cp -f *.conf /etc/redis && \
  rm -rf /tmp/redis-stable* && \
  sed -i 's/^\(bind .*\)$/# \1/' /etc/redis/redis.conf && \
  sed -i 's/^\(daemonize .*\)$/# \1/' /etc/redis/redis.conf && \
  sed -i 's/^\(dir .*\)$/# \1\ndir \/data/' /etc/redis/redis.conf && \
  sed -i 's/^\(logfile .*\)$/# \1/' /etc/redis/redis.conf

COPY conf/redis.conf /etc/redis/redis.conf

# Define mountable directories.
VOLUME ["/data"]

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["redis-server", "/etc/redis/redis.conf"]

# Expose ports.
EXPOSE 6379